import {
  AccountBox,
  Apple,
  AttachMoneyOutlined,
  BrushOutlined,
  BuildOutlined,
  CameraAlt,
  Chat,
  CheckBoxOutlined,
  Cloud,
  CloudOutlined,
  CloudUpload,
  Code,
  CreditCard,
  CreditScore,
  DeviceUnknown,
  DirectionsRun,
  Facebook,
  Fingerprint,
  FitnessCenter,
  FitnessCenterOutlined,
  Folder,
  Forum,
  Gamepad,
  GitHub,
  Google,
  HeadsetMic,
  HeadsetMicOutlined,
  ImageOutlined,
  Link,
  LinkedIn,
  LockOpenOutlined,
  LockOutlined,
  Mail,
  MapOutlined,
  Message,
  Microsoft,
  MusicNote,
  PaletteOutlined,
  Payment,
  PhoneAndroid,
  PinDrop,
  QuestionAnswer,
  Reddit,
  Restaurant,
  Share,
  ShoppingCart,
  SupervisorAccount,
  Twitter,
  VideoCall,
  VideoLibrary,
  Work,
  WorkOutlineOutlined,
  X,
} from '@mui/icons-material';
import React from 'react';
const providers = {
  Google: {
    client_id: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,
    scope: 'profile email https://www.googleapis.com/auth/gmail.send',
    uri: 'https://accounts.google.com/o/oauth2/v2/auth',
    params: {
      access_type: 'offline',
    },
    icon: <Google />,
  },
  Microsoft: {
    client_id: process.env.NEXT_PUBLIC_MICROSOFT_CLIENT_ID,
    scope:
      'https://graph.microsoft.com/User.Read https://graph.microsoft.com/Mail.Send https://graph.microsoft.com/Calendars.ReadWrite.Shared',
    uri: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
    params: {},
    icon: <Microsoft />,
  },
  GitHub: {
    client_id: process.env.NEXT_PUBLIC_GITHUB_CLIENT_ID,
    scope: 'user:email',
    uri: 'https://github.com/login/oauth/authorize',
    params: {},
    icon: <GitHub />,
  },
  Autodesk: {
    client_id: process.env.NEXT_PUBLIC_AUTODESK_CLIENT_ID,
    scope: 'data:read data:write data:create bucket:create account:read',
    uri: 'https://developer.api.autodesk.com/authentication/1/authorize',
    params: {},
    icon: <BuildOutlined />,
  },
  Dropbox: {
    client_id: process.env.NEXT_PUBLIC_DROPBOX_CLIENT_ID,
    scope: 'account_info.read files.metadata.read files.content.read',
    uri: 'https://www.dropbox.com/oauth2/authorize',
    params: {},
    icon: <CloudUpload />,
  },
  FatSecret: {
    client_id: process.env.NEXT_PUBLIC_FATSECRET_CLIENT_ID,
    scope: 'basic',
    uri: 'https://www.fatsecret.com/oauth2/authorize',
    params: {},
    icon: <Restaurant />,
  },
  Bitbucket: {
    client_id: process.env.NEXT_PUBLIC_BITBUCKET_CLIENT_ID,
    scope: 'email',
    uri: 'https://bitbucket.org/site/oauth2/authorize',
    params: {},
    icon: <Code />,
  },
  Jive: {
    client_id: process.env.NEXT_PUBLIC_JIVE_CLIENT_ID,
    scope: 'read',
    uri: 'https://acmeprod.jiveon.com/api/core/v3/authorize',
    params: {},
    icon: <Forum />,
  },
  NetIQ: {
    client_id: process.env.NEXT_PUBLIC_NETIQ_CLIENT_ID,
    scope: 'openid profile email',
    uri: 'https://idp.netiq.com/nidp/app/login',
    params: {},
    icon: <LockOutlined />,
  },
  Okta: {
    client_id: process.env.NEXT_PUBLIC_OKTA_CLIENT_ID,
    scope: 'openid profile email',
    uri: 'https://acme.oktapreview.com/oauth2/v1/authorize',
    params: {},
    icon: <Fingerprint />,
  },
  OpenStreetMap: {
    client_id: process.env.NEXT_PUBLIC_OPENSTREETMAP_CLIENT_ID,
    scope: 'read_prefs',
    uri: 'https://www.openstreetmap.org/oauth2/authorize',
    params: {},
    icon: <MapOutlined />,
  },
  Salesforce: {
    client_id: process.env.NEXT_PUBLIC_SALESFORCE_CLIENT_ID,
    scope: 'api refresh_token',
    uri: 'https://login.salesforce.com/services/oauth2/authorize',
    params: {},
    icon: <WorkOutlineOutlined />,
  },
  'WSO2 identity': {
    client_id: process.env.NEXT_PUBLIC_WSO2_CLIENT_ID,
    scope: 'openid email profile',
    uri: 'https://serverurl:9443/oauth2/authorize',
    params: {},
    icon: <Fingerprint />,
  },
  xero: {
    client_id: process.env.NEXT_PUBLIC_XERO_CLIENT_ID,
    scope: 'openid email profile offline_access',
    uri: 'https://login.xero.com/identity/connect/authorize',
    params: {},
    icon: <AttachMoneyOutlined />,
  },
  Yahoo: {
    client_id: process.env.NEXT_PUBLIC_YAHOO_CLIENT_ID,
    scope: 'openid sdx-r email',
    uri: 'https://api.login.yahoo.com/oauth2/request_auth',
    params: {},
    icon: <Mail />,
  },
  Spotify: {
    client_id: process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_ID,
    scope:
      'user-read-email user-read-private user-read-currently-playing user-read-playback-state user-modify-playback-state user-read-recently-played',
    uri: 'https://accounts.spotify.com/authorize',
    params: {},
    icon: <MusicNote />,
  },
  Facebook: {
    client_id: process.env.NEXT_PUBLIC_FACEBOOK_CLIENT_ID,
    scope: 'email',
    uri: 'https://www.facebook.com/v16.0/dialog/oauth',
    params: {},
    icon: <Facebook />,
  },
  X: {
    client_id: process.env.NEXT_PUBLIC_X_CLIENT_ID,
    scope: 'users.read tweet.read tweet.write offline.access',
    uri: 'https://twitter.com/i/oauth2/authorize',
    params: {},
    icon: <Twitter />,
  },
  Discord: {
    client_id: process.env.NEXT_PUBLIC_DISCORD_CLIENT_ID,
    scope: 'identify email',
    uri: 'https://discord.com/api/oauth2/authorize',
    params: {},
    icon: <HeadsetMic />,
  },
  LinkedIn: {
    client_id: process.env.NEXT_PUBLIC_LINKEDIN_CLIENT_ID,
    scope: 'r_emailaddress r_liteprofile',
    uri: 'https://www.linkedin.com/oauth/v2/authorization',
    params: {},
    icon: <LinkedIn />,
  },
  Apple: {
    client_id: process.env.NEXT_PUBLIC_APPLE_CLIENT_ID,
    scope: 'name email',
    uri: 'https://appleid.apple.com/auth/authorize',
    params: {},
    icon: <Apple />,
  },
  Slack: {
    client_id: process.env.NEXT_PUBLIC_SLACK_CLIENT_ID,
    scope: 'users:read users:read.email',
    uri: 'https://slack.com/oauth/v2/authorize',
    params: {},
    icon: <Message />,
  },
  Twitch: {
    client_id: process.env.NEXT_PUBLIC_TWITCH_CLIENT_ID,
    scope: 'user:read:email',
    uri: 'https://id.twitch.tv/oauth2/authorize',
    params: {},
    icon: <VideoCall />,
  },
  Amazon: {
    client_id: process.env.NEXT_PUBLIC_AMAZON_CLIENT_ID,
    scope: 'profile',
    uri: 'https://www.amazon.com/ap/oa',
    params: {},
    icon: <ShoppingCart />,
  },
  Steam: {
    client_id: process.env.NEXT_PUBLIC_STEAM_CLIENT_ID,
    scope: 'openid',
    uri: 'https://steamcommunity.com/openid/login',
    params: {},
    icon: <Gamepad />,
  },

  AOL: {
    client_id: process.env.NEXT_PUBLIC_AOL_CLIENT_ID,
    scope: 'profile email',
    uri: 'https://api.screenname.aol.com/auth/authorize',
    params: {},
    icon: <Mail />,
  },
  Basecamp: {
    client_id: process.env.NEXT_PUBLIC_BASECAMP_CLIENT_ID,
    scope: 'access',
    uri: 'https://launchpad.37signals.com/authorization/new',
    params: {},
    icon: <Work />,
  },
  'Battle.net': {
    client_id: process.env.NEXT_PUBLIC_BATTLENET_CLIENT_ID,
    scope: 'openid',
    uri: 'https://battlenet.com.cn/oauth/',
    params: {},
    icon: <Gamepad />,
  },
  bitly: {
    client_id: process.env.NEXT_PUBLIC_BITLY_CLIENT_ID,
    scope: 'default',
    uri: 'https://bitly.com/oauth/authorize',
    params: {},
    icon: <Link />,
  },
  Box: {
    client_id: process.env.NEXT_PUBLIC_BOX_CLIENT_ID,
    scope: 'root_readwrite',
    uri: 'https://account.box.com/api/oauth2/authorize',
    params: {},
    icon: <Folder />,
  },
  ClearScore: {
    client_id: process.env.NEXT_PUBLIC_CLEARSCORE_CLIENT_ID,
    scope: 'accounts:read kyc:read',
    uri: 'https://api.clearscore.com/oauth/authorize',
    params: {},
    icon: <CreditScore />,
  },
  'Cloud Foundry': {
    client_id: process.env.NEXT_PUBLIC_CLOUDFOUNDRY_CLIENT_ID,
    scope: 'cloud_controller_service_permissions.read',
    uri: 'https://login.run.pivotal.io/oauth/authorize',
    params: {},
    icon: <Cloud />,
  },
  Dailymotion: {
    client_id: process.env.NEXT_PUBLIC_DAILYMOTION_CLIENT_ID,
    scope: 'email',
    uri: 'https://www.dailymotion.com/oauth/authorize',
    params: {},
    icon: <VideoLibrary />,
  },
  'Deutsche Telekom': {
    client_id: process.env.NEXT_PUBLIC_DEUTSCHETELEKOM_CLIENT_ID,
    scope: 'openid',
    uri: 'https://accounts.login.idm.telekom.com/oauth2/authorize',
    params: {},
    icon: <PhoneAndroid />,
  },
  deviantART: {
    client_id: process.env.NEXT_PUBLIC_DEVIANTART_CLIENT_ID,
    scope: 'browse basicdata email',
    uri: 'https://www.deviantart.com/oauth2/draft15/authorize',
    params: {},
    icon: <BrushOutlined />,
  },
  Fitbit: {
    client_id: process.env.NEXT_PUBLIC_FITBIT_CLIENT_ID,
    scope: 'activity heartrate location nutrition profile settings sleep view_activity',
    uri: 'https://www.fitbit.com/oauth2/authorize',
    params: {},
    icon: <FitnessCenter />,
  },
  Formstack: {
    client_id: process.env.NEXT_PUBLIC_FORMSTACK_CLIENT_ID,
    scope: 'openid',
    uri: 'https://auth.formstack.com/authorize',
    params: {},
    icon: <CheckBoxOutlined />,
  },
  Foursquare: {
    client_id: process.env.NEXT_PUBLIC_FOURSQUARE_CLIENT_ID,
    scope: 'email',
    uri: 'https://foursquare.com/oauth2/authenticate',
    params: {},
    icon: <PinDrop />,
  },
  GitLab: {
    client_id: process.env.NEXT_PUBLIC_GITLAB_CLIENT_ID,
    scope: 'read_user',
    uri: 'https://gitlab.com/oauth/authorize',
    params: {},
    icon: <Code />,
  },
  Huddle: {
    client_id: process.env.NEXT_PUBLIC_HUDDLE_CLIENT_ID,
    scope: 'user:email user:profile:full user:content:full',
    uri: 'https://huddle.eu/login',
    params: {},
    icon: <SupervisorAccount />,
  },
  Imgur: {
    client_id: process.env.NEXT_PUBLIC_IMGUR_CLIENT_ID,
    scope: 'email',
    uri: 'https://api.imgur.com/oauth2/authorize',
    params: {},
    icon: <ImageOutlined />,
  },
  Instagram: {
    client_id: process.env.NEXT_PUBLIC_INSTAGRAM_CLIENT_ID,
    scope: 'user_profile,user_media',
    uri: 'https://api.instagram.com/oauth/authorize',
    params: {},
    icon: <CameraAlt />,
  },
  'Intel Cloud Services': {
    client_id: process.env.NEXT_PUBLIC_INTELCLOUDSERVICES_CLIENT_ID,
    scope: 'openid user/info.me cloudaccess',
    uri: 'https://cloudlogin.01.intrinsicsecure.com/authorize',
    params: {},
    icon: <CloudOutlined />,
  },
  Keycloak: {
    client_id: process.env.NEXT_PUBLIC_KEYCLOAK_CLIENT_ID,
    scope: 'openid',
    uri: 'https://keycloak.example.com/auth/realms/myrealm/protocol/openid-connect/auth',
    params: {},
    icon: <LockOutlined />,
  },
  OpenAM: {
    client_id: process.env.NEXT_PUBLIC_OPENAM_CLIENT_ID,
    scope: 'fr:idm:*',
    uri: 'https://openam.example.com/oauth2/authorize.jsp',
    params: {},
    icon: <LockOpenOutlined />,
  },
  ORCID: {
    client_id: process.env.NEXT_PUBLIC_ORCID_CLIENT_ID,
    scope: '/read-public',
    uri: 'https://orcid.org/oauth/authorize',
    params: {},
    icon: <AccountBox />,
  },
  PayPal: {
    client_id: process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID,
    scope: 'openid email https://uri.paypal.com/services/paypalattributes',
    uri: 'https://www.paypal.com/signin/authorize',
    params: {},
    icon: <Payment />,
  },
  'Ping Identity': {
    client_id: process.env.NEXT_PUBLIC_PINGIDENTITY_CLIENT_ID,
    scope: 'openid profile email',
    uri: 'https://sso.pingone.com/XXXXXXXXXXXXX/as/authorization.oauth2',
    params: {},
    icon: <Fingerprint />,
  },
  Pixiv: {
    client_id: process.env.NEXT_PUBLIC_PIXIV_CLIENT_ID,
    scope: 'user:read',
    uri: 'https://accounts.pixiv.net/oauth2/authorize',
    params: {},
    icon: <PaletteOutlined />,
  },
  Reddit: {
    client_id: process.env.NEXT_PUBLIC_REDDIT_CLIENT_ID,
    scope: 'identity',
    uri: 'https://www.reddit.com/api/v1/authorize',
    params: {},
    icon: <Reddit />,
  },
  'Sina Weibo': {
    client_id: process.env.NEXT_PUBLIC_SINAWEIBO_CLIENT_ID,
    scope: 'email',
    uri: 'https://api.weibo.com/oauth2/authorize',
    params: {},
    icon: <Share />,
  },
  'Stack Exchange': {
    client_id: process.env.NEXT_PUBLIC_STACKEXCHANGE_CLIENT_ID,
    scope: 'no_expiry',
    uri: 'https://stackexchange.com/oauth',
    params: {},
    icon: <QuestionAnswer />,
  },
  Strava: {
    client_id: process.env.NEXT_PUBLIC_STRAVA_CLIENT_ID,
    scope: 'activity:read_all',
    uri: 'https://www.strava.com/oauth/authorize',
    params: {},
    icon: <DirectionsRun />,
  },
  Stripe: {
    client_id: process.env.NEXT_PUBLIC_STRIPE_CLIENT_ID,
    scope: 'read_write',
    uri: 'https://connect.stripe.com/oauth/authorize',
    params: {},
    icon: <CreditCard />,
  },
  Viadeo: {
    client_id: process.env.NEXT_PUBLIC_VIADEO_CLIENT_ID,
    scope: 'access',
    uri: 'https://www.viadeo.com/oauth-provider/authorize2',
    params: {},
    icon: <Work />,
  },
  Vimeo: {
    client_id: process.env.NEXT_PUBLIC_VIMEO_CLIENT_ID,
    scope: 'public',
    uri: 'https://api.vimeo.com/oauth/authorize',
    params: {},
    icon: <VideoCall />,
  },
  VK: {
    client_id: process.env.NEXT_PUBLIC_VK_CLIENT_ID,
    scope: 'email',
    uri: 'https://oauth.vk.com/authorize',
    params: {},
    icon: <DeviceUnknown />,
  },
  WeChat: {
    client_id: process.env.NEXT_PUBLIC_WECHAT_CLIENT_ID,
    scope: 'snsapi_login',
    uri: 'https://open.weixin.qq.com/connect/qrconnect',
    params: {},
    icon: <Chat />,
  },
  Withings: {
    client_id: process.env.NEXT_PUBLIC_WITHINGS_CLIENT_ID,
    scope: 'user.info',
    uri: 'https://account.withings.com/oauth2_user/authorize2',
    params: {},
    icon: <FitnessCenterOutlined />,
  },
  XING: {
    client_id: process.env.NEXT_PUBLIC_XING_CLIENT_ID,
    scope: 'openid',
    uri: 'https://login.xing.com/authorize',
    params: {},
    icon: <WorkOutlineOutlined />,
  },
  Yammer: {
    client_id: process.env.NEXT_PUBLIC_YAMMER_CLIENT_ID,
    scope: 'user_details',
    uri: 'https://www.yammer.com/oauth2/authorize',
    params: {},
    icon: <Forum />,
  },
  Yandex: {
    client_id: process.env.NEXT_PUBLIC_YANDEX_CLIENT_ID,
    scope: 'login:email',
    uri: 'https://oauth.yandex.com/authorize',
    params: {},
    icon: <DeviceUnknown />,
  },
  Yelp: {
    client_id: process.env.NEXT_PUBLIC_YELP_CLIENT_ID,
    scope: 'email',
    uri: 'https://www.yelp.com/oauth2/authorize',
    params: {},
    icon: <Restaurant />,
  },
  Zendesk: {
    client_id: process.env.NEXT_PUBLIC_ZENDESK_CLIENT_ID,
    scope: 'read',
    uri: 'https://YOURSUBDOMAIN.zendesk.com/oauth/authorize',
    params: {},
    icon: <HeadsetMicOutlined />,
  },
};
export default providers;
